version: '3.7'
services:
  app:
    image: golang:1.13.0
    command: go run main.go
    volumes:
      - ./src:/go/src
      - ./tests:/go/tests
    working_dir: /go/src
    ports:
      - "3001:3000"
  elasticsearch:
    image: elasticsearch:7.3.2
    restart: always
    environment:
      - discovery.type=single-node
    ports:
     - "9200:9200"